/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GenerateVideoRouteImport } from './routes/generate-video'
import { Route as GenerateImageRouteImport } from './routes/generate-image'
import { Route as IndexRouteImport } from './routes/index'

const GenerateVideoRoute = GenerateVideoRouteImport.update({
  id: '/generate-video',
  path: '/generate-video',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateImageRoute = GenerateImageRouteImport.update({
  id: '/generate-image',
  path: '/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generate-image': typeof GenerateImageRoute
  '/generate-video': typeof GenerateVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generate-image': typeof GenerateImageRoute
  '/generate-video': typeof GenerateVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/generate-image': typeof GenerateImageRoute
  '/generate-video': typeof GenerateVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/generate-image' | '/generate-video'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/generate-image' | '/generate-video'
  id: '__root__' | '/' | '/generate-image' | '/generate-video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenerateImageRoute: typeof GenerateImageRoute
  GenerateVideoRoute: typeof GenerateVideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/generate-video': {
      id: '/generate-video'
      path: '/generate-video'
      fullPath: '/generate-video'
      preLoaderRoute: typeof GenerateVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate-image': {
      id: '/generate-image'
      path: '/generate-image'
      fullPath: '/generate-image'
      preLoaderRoute: typeof GenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenerateImageRoute: GenerateImageRoute,
  GenerateVideoRoute: GenerateVideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
